version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: todo-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  flask:
    build:
      context: .
    container_name: flask-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - - MONGO_URI_DEV=mongodb://todo-mongo:27017/todo_db
      - - SECRET_KEY=123abc456def
      - - FLASK_ENV=development
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
